version: '3'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile-front
    container_name: front
    ports:
      - "443:443"
  app:
    image: grtgaz/inca
    container_name: app
    environment:
      - AUTHENTIFICATION_ACTIVE=false